// This file is automatically generated. Do not edit it directly.
// Powered by EnterCloud Managed Supabase
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://mdewakadxwgxigijmcxe.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kZXdha2FkeHdneGlnaWptY3hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU3NjQyMzQsImV4cCI6MjEwMTM0MDIzNH0.XWh9QwMbkSaOhXXrEtoJ6liKIhUjdB-hfp-IeJ2XAyM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
